# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: william a. f. mvkete
email: hello@mukete.ninja
description: > # this means to ignore newlines until "baseurl:"
  Mukete, software engineer, web developer and all things awesome + ninja.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mukete.github.io" # the base hostname & protocol for your site
twitter_username: mvkete
github_username:  mukete

# Build settings
markdown: kramdown
